spring:
  application:
    name: friends-agenda

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:admin123@localhost:27017/friends_agenda?authSource=admin}

  datasource:
    url: jdbc:mysql://localhost:3306/friends_agenda?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: friends
    password: friends123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

app:
  data:
    schemaVersion: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info
